from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ExperimentSpec:
    name: str
    epochs: int
    width: float
    depth: tuple[int, int]
    kernel: int
    tasks: tuple[str, ...]
    notes: str


EXPERIMENTS = (
    ExperimentSpec(
        "study_001",
        600,
        0.625,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 001",
    ),
    ExperimentSpec(
        "study_002",
        600,
        0.75,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 002",
    ),
    ExperimentSpec(
        "study_003",
        600,
        0.875,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 003",
    ),
    ExperimentSpec(
        "study_004",
        600,
        1.0,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 004",
    ),
    ExperimentSpec(
        "study_005",
        600,
        0.5,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 005",
    ),
    ExperimentSpec(
        "study_006",
        600,
        0.625,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 006",
    ),
    ExperimentSpec(
        "study_007",
        600,
        0.75,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 007",
    ),
    ExperimentSpec(
        "study_008",
        600,
        0.875,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 008",
    ),
    ExperimentSpec(
        "study_009",
        600,
        1.0,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 009",
    ),
    ExperimentSpec(
        "study_010",
        600,
        0.5,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 010",
    ),
    ExperimentSpec(
        "study_011",
        600,
        0.625,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 011",
    ),
    ExperimentSpec(
        "study_012",
        600,
        0.75,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 012",
    ),
    ExperimentSpec(
        "study_013",
        600,
        0.875,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 013",
    ),
    ExperimentSpec(
        "study_014",
        600,
        1.0,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 014",
    ),
    ExperimentSpec(
        "study_015",
        600,
        0.5,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 015",
    ),
    ExperimentSpec(
        "study_016",
        600,
        0.625,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 016",
    ),
    ExperimentSpec(
        "study_017",
        600,
        0.75,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 017",
    ),
    ExperimentSpec(
        "study_018",
        600,
        0.875,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 018",
    ),
    ExperimentSpec(
        "study_019",
        600,
        1.0,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 019",
    ),
    ExperimentSpec(
        "study_020",
        600,
        0.5,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 020",
    ),
    ExperimentSpec(
        "study_021",
        600,
        0.625,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 021",
    ),
    ExperimentSpec(
        "study_022",
        600,
        0.75,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 022",
    ),
    ExperimentSpec(
        "study_023",
        600,
        0.875,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 023",
    ),
    ExperimentSpec(
        "study_024",
        600,
        1.0,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 024",
    ),
    ExperimentSpec(
        "study_025",
        600,
        0.5,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 025",
    ),
    ExperimentSpec(
        "study_026",
        600,
        0.625,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 026",
    ),
    ExperimentSpec(
        "study_027",
        600,
        0.75,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 027",
    ),
    ExperimentSpec(
        "study_028",
        600,
        0.875,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 028",
    ),
    ExperimentSpec(
        "study_029",
        600,
        1.0,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 029",
    ),
    ExperimentSpec(
        "study_030",
        600,
        0.5,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 030",
    ),
    ExperimentSpec(
        "study_031",
        600,
        0.625,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 031",
    ),
    ExperimentSpec(
        "study_032",
        600,
        0.75,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 032",
    ),
    ExperimentSpec(
        "study_033",
        600,
        0.875,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 033",
    ),
    ExperimentSpec(
        "study_034",
        600,
        1.0,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 034",
    ),
    ExperimentSpec(
        "study_035",
        600,
        0.5,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 035",
    ),
    ExperimentSpec(
        "study_036",
        600,
        0.625,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 036",
    ),
    ExperimentSpec(
        "study_037",
        600,
        0.75,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 037",
    ),
    ExperimentSpec(
        "study_038",
        600,
        0.875,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 038",
    ),
    ExperimentSpec(
        "study_039",
        600,
        1.0,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 039",
    ),
    ExperimentSpec(
        "study_040",
        600,
        0.5,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 040",
    ),
    ExperimentSpec(
        "study_041",
        600,
        0.625,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 041",
    ),
    ExperimentSpec(
        "study_042",
        600,
        0.75,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 042",
    ),
    ExperimentSpec(
        "study_043",
        600,
        0.875,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 043",
    ),
    ExperimentSpec(
        "study_044",
        600,
        1.0,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 044",
    ),
    ExperimentSpec(
        "study_045",
        600,
        0.5,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 045",
    ),
    ExperimentSpec(
        "study_046",
        600,
        0.625,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 046",
    ),
    ExperimentSpec(
        "study_047",
        600,
        0.75,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 047",
    ),
    ExperimentSpec(
        "study_048",
        600,
        0.875,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 048",
    ),
    ExperimentSpec(
        "study_049",
        600,
        1.0,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 049",
    ),
    ExperimentSpec(
        "study_050",
        600,
        0.5,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 050",
    ),
    ExperimentSpec(
        "study_051",
        600,
        0.625,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 051",
    ),
    ExperimentSpec(
        "study_052",
        600,
        0.75,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 052",
    ),
    ExperimentSpec(
        "study_053",
        600,
        0.875,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 053",
    ),
    ExperimentSpec(
        "study_054",
        600,
        1.0,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 054",
    ),
    ExperimentSpec(
        "study_055",
        600,
        0.5,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 055",
    ),
    ExperimentSpec(
        "study_056",
        600,
        0.625,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 056",
    ),
    ExperimentSpec(
        "study_057",
        600,
        0.75,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 057",
    ),
    ExperimentSpec(
        "study_058",
        600,
        0.875,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 058",
    ),
    ExperimentSpec(
        "study_059",
        600,
        1.0,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 059",
    ),
    ExperimentSpec(
        "study_060",
        600,
        0.5,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 060",
    ),
    ExperimentSpec(
        "study_061",
        600,
        0.625,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 061",
    ),
    ExperimentSpec(
        "study_062",
        600,
        0.75,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 062",
    ),
    ExperimentSpec(
        "study_063",
        600,
        0.875,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 063",
    ),
    ExperimentSpec(
        "study_064",
        600,
        1.0,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 064",
    ),
    ExperimentSpec(
        "study_065",
        600,
        0.5,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 065",
    ),
    ExperimentSpec(
        "study_066",
        600,
        0.625,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 066",
    ),
    ExperimentSpec(
        "study_067",
        600,
        0.75,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 067",
    ),
    ExperimentSpec(
        "study_068",
        600,
        0.875,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 068",
    ),
    ExperimentSpec(
        "study_069",
        600,
        1.0,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 069",
    ),
    ExperimentSpec(
        "study_070",
        600,
        0.5,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 070",
    ),
    ExperimentSpec(
        "study_071",
        600,
        0.625,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 071",
    ),
    ExperimentSpec(
        "study_072",
        600,
        0.75,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 072",
    ),
    ExperimentSpec(
        "study_073",
        600,
        0.875,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 073",
    ),
    ExperimentSpec(
        "study_074",
        600,
        1.0,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 074",
    ),
    ExperimentSpec(
        "study_075",
        600,
        0.5,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 075",
    ),
    ExperimentSpec(
        "study_076",
        600,
        0.625,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 076",
    ),
    ExperimentSpec(
        "study_077",
        600,
        0.75,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 077",
    ),
    ExperimentSpec(
        "study_078",
        600,
        0.875,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 078",
    ),
    ExperimentSpec(
        "study_079",
        600,
        1.0,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 079",
    ),
    ExperimentSpec(
        "study_080",
        600,
        0.5,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 080",
    ),
    ExperimentSpec(
        "study_081",
        600,
        0.625,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 081",
    ),
    ExperimentSpec(
        "study_082",
        600,
        0.75,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 082",
    ),
    ExperimentSpec(
        "study_083",
        600,
        0.875,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 083",
    ),
    ExperimentSpec(
        "study_084",
        600,
        1.0,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 084",
    ),
    ExperimentSpec(
        "study_085",
        600,
        0.5,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 085",
    ),
    ExperimentSpec(
        "study_086",
        600,
        0.625,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 086",
    ),
    ExperimentSpec(
        "study_087",
        600,
        0.75,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 087",
    ),
    ExperimentSpec(
        "study_088",
        600,
        0.875,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 088",
    ),
    ExperimentSpec(
        "study_089",
        600,
        1.0,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 089",
    ),
    ExperimentSpec(
        "study_090",
        600,
        0.5,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 090",
    ),
    ExperimentSpec(
        "study_091",
        600,
        0.625,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 091",
    ),
    ExperimentSpec(
        "study_092",
        600,
        0.75,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 092",
    ),
    ExperimentSpec(
        "study_093",
        600,
        0.875,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 093",
    ),
    ExperimentSpec(
        "study_094",
        600,
        1.0,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 094",
    ),
    ExperimentSpec(
        "study_095",
        600,
        0.5,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 095",
    ),
    ExperimentSpec(
        "study_096",
        600,
        0.625,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 096",
    ),
    ExperimentSpec(
        "study_097",
        600,
        0.75,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 097",
    ),
    ExperimentSpec(
        "study_098",
        600,
        0.875,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 098",
    ),
    ExperimentSpec(
        "study_099",
        600,
        1.0,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 099",
    ),
    ExperimentSpec(
        "study_100",
        600,
        0.5,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 100",
    ),
    ExperimentSpec(
        "study_101",
        600,
        0.625,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 101",
    ),
    ExperimentSpec(
        "study_102",
        600,
        0.75,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 102",
    ),
    ExperimentSpec(
        "study_103",
        600,
        0.875,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 103",
    ),
    ExperimentSpec(
        "study_104",
        600,
        1.0,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 104",
    ),
    ExperimentSpec(
        "study_105",
        600,
        0.5,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 105",
    ),
    ExperimentSpec(
        "study_106",
        600,
        0.625,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 106",
    ),
    ExperimentSpec(
        "study_107",
        600,
        0.75,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 107",
    ),
    ExperimentSpec(
        "study_108",
        600,
        0.875,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 108",
    ),
    ExperimentSpec(
        "study_109",
        600,
        1.0,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 109",
    ),
    ExperimentSpec(
        "study_110",
        600,
        0.5,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 110",
    ),
    ExperimentSpec(
        "study_111",
        600,
        0.625,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 111",
    ),
    ExperimentSpec(
        "study_112",
        600,
        0.75,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 112",
    ),
    ExperimentSpec(
        "study_113",
        600,
        0.875,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 113",
    ),
    ExperimentSpec(
        "study_114",
        600,
        1.0,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 114",
    ),
    ExperimentSpec(
        "study_115",
        600,
        0.5,
        (2, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 115",
    ),
    ExperimentSpec(
        "study_116",
        600,
        0.625,
        (3, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 116",
    ),
    ExperimentSpec(
        "study_117",
        600,
        0.75,
        (2, 1),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 117",
    ),
    ExperimentSpec(
        "study_118",
        600,
        0.875,
        (2, 2),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 118",
    ),
    ExperimentSpec(
        "study_119",
        600,
        1.0,
        (3, 2),
        5,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 119",
    ),
    ExperimentSpec(
        "study_120",
        600,
        0.5,
        (2, 1),
        3,
        ("burden", "efficacy", "pneumonitis"),
        "registered configuration 120",
    ),
)


def experiment_by_name(name: str) -> ExperimentSpec:
    for experiment in EXPERIMENTS:
        if experiment.name == name:
            return experiment
    raise KeyError(name)
